name: CI

on:
  push:
    paths:
      - 'bucket/*.json'
      - 'bin/lint.ps1'
    branches:
      - main
  pull_request:
    paths:
      - 'bucket/*.json'
      - 'bin/lint.ps1'

permissions:
  contents: read

jobs:
  validate:
    name: Validate
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5

      - name: Lint Manifests
        shell: pwsh
        run: pwsh bin/lint.ps1 -CI
